# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table8',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
